language: java
jdk:
    - oraclejdk11

sudo: false

notifications:
  email:
    recipients:
      - info@softinstigate.com
    on_success: change
    on_failure: always
  slack: s-i:fgs1E6lggHh7JNFFqGMsWTPz

cache:
  directories:
     - '$HOME/.m2'
     
install: true
script: mvn clean install
