language: java
jdk:
    - openjdk11
git:
  depth: 3

sudo: false

services:
  - docker

notifications:
  email:
    recipients:
      - info@softinstigate.com
    on_success: change
    on_failure: always
  slack: s-i:fgs1E6lggHh7JNFFqGMsWTPz

cache:
  directories:
     - '$HOME/.m2'
     
install: true
script: mvn clean install

after_success: ./bin/push.sh
