language: java
jdk:
    - openjdk8
    
sudo: false

notifications:
  email:
    recipients:
      - info@softinstigate.com
    on_success: always
  slack: s-i:fgs1E6lggHh7JNFFqGMsWTPz

cache:
  directories:
     - '$HOME/.m2'
     
install: true
script: mvn clean install
