## configuration file for RESTHeart integration  test suite
---
users:
    - userid: user1
      password: changeit
      roles: [powerusers]

    - userid: user2
      password: changeit
      roles: [users]

    - userid: admin
      password: changeit
      roles: [users, admins]

permissions:
    - role: admins
      predicate: path-prefix[path="/"]

    - role: $unauthenticated
      predicate: path-prefix[path="/testdb/refcoll1"] and method[value="GET"]

    - role: powerusers
      predicate: path-prefix[path="/testdb"] and method[value="GET"]

    - role: powerusers
      predicate: path-prefix[path="/testmytmpdb"]

    - role: users
      predicate: path-prefix[path="/testdb/refcoll2"] and method[value="GET"]

    - role: users
      predicate: path[path="/testdb/refcoll2"] and method[value="GET"]

    - role: users
      predicate: (path[path="/testtmpdb2"] or path[path="/testtmpdb3"]) and method[value="PUT"]

    # This to check the path-template predicate
    - role: users
      predicate: path-template[value="/testtmpdb2/{username}"] and equals[%u, "${username}"]

    # This to check the regex predicate
    - role: users
      predicate: regex[pattern="/testtmpdb3/(.*?)", value="%R", full-match=true] and equals[%u, "${1}"]
